package com.yz.ams.client;


import com.calendarfx.util.CalendarFX;
import com.yz.ams.client.util.ClientUtils;
import com.nazca.ui.InternalDiagTool;
import com.nazca.ui.laf.NazcaLAFTool;
import com.nazca.util.TimeFairy;
import java.awt.BorderLayout;
import javax.swing.SwingUtilities;

/*
 * NewJFrame.java
 * 
 * Copyright(c) 2007-2016 by Yingzhi Tech
 * All Rights Reserved
 * 
 * Created at 2016-01-12 09:53:35
 */

/**
 *
 * @author Zhu Mengchao
 */
public class ClientMainFrame extends javax.swing.JFrame {
    private LoginPanel loginPane = new LoginPanel();
    private WorkplacePanel workplacePane = null;
//    private NProcessingPanel logoutPane;
    /**
     * Creates new form NewJFrame
     */
    public ClientMainFrame() {
        initComponents();
        CalendarFX.setLicenseKey("LIC=CO_24;VEN=ComponentSource;VER=STANDARD;PRO=1;RUN=no;CTR=0;SignCode=3F;Signature=302D02147D42F7F46938EF031E080B9F4AB3DE76FE709213021500913D47CB73AE23411EC840E00FDD2B54B6868DAF");
        ClientContext.setMainFrame(this);
        this.setTitle("考勤管理系统");
        this.setIconImage(ClientUtils.buildBufferedImage("logo-16.png"));
        this.gotoLogin();
//        this.add(new LoginPanel());
//        this.setSize(1000, 750);
//        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//        this.setLocationRelativeTo(null);
    }
    
    public void gotoWorkplace() {
        workplacePane = new WorkplacePanel();
        this.getContentPane().removeAll();
        this.getContentPane().add(workplacePane, BorderLayout.CENTER);
        validate();
        repaint();
    }
    
    public void gotoLogout() {
        workplacePane = null;
        logoutPane.setIndeterminate(true);
        InternalDiagTool.showInternalDiag(this, logoutPane, "注销中...", null, 120,
                100);
        new Thread("Logout-Thread") {
            @Override
            public void run() {
                new TimeFairy(500).sleepIfNecessary();
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        ClientMainFrame.this.gotoLogin();
                        InternalDiagTool.hideInternalDiag(logoutPane);
                        logoutPane.setIndeterminate(false);
                    }
                });
            }
        }.start();
    }
    private void gotoLogin() {
        this.getContentPane().removeAll();
        loginPane.setEmptyMsgLb();
        loginPane.loadUserAndPwd();
        loginPane.setUserAndPwd();
        this.getContentPane().add(loginPane, BorderLayout.CENTER);
        validate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutPane = new com.nazca.ui.NProcessingPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        NazcaLAFTool.applyNazcaLAF();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ClientMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.nazca.ui.NProcessingPanel logoutPane;
    // End of variables declaration//GEN-END:variables
}
