/*
 * ShowSickVacationPanel.java
 * 
 * Copyright(c) 2007-2016 by Yingzhi Tech
 * All Rights Reserved
 * 
 * Created at 2016-07-07 18:43:59
 */
package com.yz.ams.client.ui.vacation;

import com.nazca.ui.NInternalDiag;
import com.yz.ams.client.util.ClientUtils;
import com.yz.ams.model.Vacation;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import javax.swing.JComponent;
import javax.swing.WindowConstants;

/**
 *
 * @author 赵洪坤 <zhaohongkun@yzhtech.com>
 */
public class ShowSickVacationPanel extends javax.swing.JPanel {
    private NInternalDiag<Vacation, JComponent> diag = null;
    /**
     * Creates new form showSickVacationPanel
     */
    public ShowSickVacationPanel() {
        initComponents();
    }
    public void setPicResult(BufferedImage backCurImage) {
        BufferedImage newImage = new BufferedImage(900, 680, backCurImage.getType());
        Graphics g = newImage.getGraphics();
        g.drawImage(backCurImage, 0, 0, 900, 680, null);
        g.dispose();
        backCurImage = newImage;
        nImagePanel1.setImage(backCurImage);
    }
    public Vacation showMe(JComponent parent) {
        diag = new NInternalDiag<Vacation, JComponent>("病假证明单", ClientUtils.buildImageIcon(""), this, 690, 520);
        diag.setCloseButtonVisible(true);
        diag.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE); 
        return diag.showInternalDiag(parent);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nImagePanel1 = new com.nazca.ui.NImagePanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(nImagePanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(nImagePanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.nazca.ui.NImagePanel nImagePanel1;
    // End of variables declaration//GEN-END:variables
}
