/*
 * AboutPanel.java
 * 
 * Copyright(c) 2007-2016 by Yingzhi Tech
 * All Rights Reserved
 * 
 * Created at 2016-07-01 16:18:00
 */
package com.yz.ams.client.ui;

import com.nazca.ui.NDebugConsolePanel;
import com.nazca.ui.NInternalDiag;
import com.nazca.ui.UIUtilities;
import com.yz.ams.util.VersionHelper;
import javax.swing.JComponent;

/**
 * 关于面板
 * @author Qiu Dongyue
 */
public class AboutPanel extends javax.swing.JPanel {

    /**
     * Creates new form AboutBheem
     */
    public AboutPanel() {
        initComponents();
        versionLb.setText("版本：" + VersionHelper.getTotalVersion());
    }

    public void showMe(JComponent parent) {
        NInternalDiag diag = new NInternalDiag("关于", null, this);
        diag.showInternalDiag(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        copyrightLb = new javax.swing.JLabel();
        logoLb = new javax.swing.JLabel();
        versionLb = new javax.swing.JLabel();
        jLinkLabel1 = new com.nazca.ui.JLinkLabel();
        copyrightLb1 = new javax.swing.JLabel();
        copyrightLb2 = new javax.swing.JLabel();

        copyrightLb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        copyrightLb.setToolTipText("版权所有：");
        copyrightLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        logoLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/yz/ams/client/res/logo_big.png"))); // NOI18N
        logoLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoLbMouseClicked(evt);
            }
        });

        versionLb.setForeground(new java.awt.Color(102, 102, 102));
        versionLb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        versionLb.setText("版本：1.1.2.529");

        jLinkLabel1.setText("关闭“关于”");
        jLinkLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLinkLabel1MousePressed(evt);
            }
        });

        copyrightLb1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        copyrightLb1.setText("版权所有：北京英智兴达信息技术有限公司");
        copyrightLb1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        copyrightLb2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        copyrightLb2.setText("技术支持：北京英智兴达信息技术有限公司");
        copyrightLb2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(logoLb, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLinkLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(copyrightLb2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(copyrightLb1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(versionLb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(copyrightLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLb, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(versionLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyrightLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyrightLb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyrightLb2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLinkLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLinkLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLinkLabel1MousePressed
        NInternalDiag diag = NInternalDiag.findNInternalDiag(this);
        diag.hideDiag();
    }//GEN-LAST:event_jLinkLabel1MousePressed

    private void logoLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoLbMouseClicked
        if (UIUtilities.isLeftDoubleClick(evt)) {
            NDebugConsolePanel.showConsoleWindow();
        }
    }//GEN-LAST:event_logoLbMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel copyrightLb;
    private javax.swing.JLabel copyrightLb1;
    private javax.swing.JLabel copyrightLb2;
    private com.nazca.ui.JLinkLabel jLinkLabel1;
    private javax.swing.JLabel logoLb;
    private javax.swing.JLabel versionLb;
    // End of variables declaration//GEN-END:variables
}
