package com.yz.ams.client.ui;

import com.yz.ams.client.ui.attendence.AttendanceMgmtPanel;
import com.yz.ams.client.ui.biztrip.BizTripMgmtPanel;
import com.yz.ams.client.ui.rest.RestMgmtPanel;
import com.yz.ams.client.ui.vacation.VacationMgmtPanel;
import com.nazca.ui.NImagePanel;
import com.nazca.ui.NTabContentPanel;
import java.awt.BorderLayout;

/*
 * AttendPanel.java
 * 
 * Copyright(c) 2007-2016 by Yingzhi Tech
 * All Rights Reserved
 * 
 * Created at 2016-01-08 15:18:54
 */

/**
 *
 * @author Your Name <Song Haixiang >
 */
public class AttendanceInfoMgmtTabPanel extends NTabContentPanel {
    private VacationMgmtPanel vacationMgmtPane = new VacationMgmtPanel();
    private BizTripMgmtPanel bizTripMgmtPane =new BizTripMgmtPanel();
    private RestMgmtPanel restMgmtPanel = new RestMgmtPanel();
    private AttendanceMgmtPanel attendanceMgmtPanel = new AttendanceMgmtPanel();

    /**
     * Creates new form AttendPanel
     */
    public AttendanceInfoMgmtTabPanel() {
        initComponents();
        NImagePanel imagePane = new NImagePanel();
        setTabText("考勤信息管理");
        VacationTgBtn.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        nNavToolBar1 = new com.nazca.ui.NNavToolBar();
        VacationTgBtn = new javax.swing.JToggleButton();
        BizTripManageTgBtn = new javax.swing.JToggleButton();
        RestManageTgBtn = new javax.swing.JToggleButton();
        AttendanceManageTgBtn = new javax.swing.JToggleButton();
        jPanel16 = new javax.swing.JPanel();

        nNavToolBar1.setRollover(true);

        buttonGroup1.add(VacationTgBtn);
        VacationTgBtn.setText("请假管理");
        VacationTgBtn.setFocusable(false);
        VacationTgBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        VacationTgBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        VacationTgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VacationTgBtnActionPerformed(evt);
            }
        });
        nNavToolBar1.add(VacationTgBtn);

        buttonGroup1.add(BizTripManageTgBtn);
        BizTripManageTgBtn.setText("出差管理");
        BizTripManageTgBtn.setFocusable(false);
        BizTripManageTgBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BizTripManageTgBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BizTripManageTgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BizTripManageTgBtnActionPerformed(evt);
            }
        });
        nNavToolBar1.add(BizTripManageTgBtn);

        buttonGroup1.add(RestManageTgBtn);
        RestManageTgBtn.setText("调休管理");
        RestManageTgBtn.setFocusable(false);
        RestManageTgBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RestManageTgBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RestManageTgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestManageTgBtnActionPerformed(evt);
            }
        });
        nNavToolBar1.add(RestManageTgBtn);

        buttonGroup1.add(AttendanceManageTgBtn);
        AttendanceManageTgBtn.setText("出勤管理");
        AttendanceManageTgBtn.setFocusable(false);
        AttendanceManageTgBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AttendanceManageTgBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AttendanceManageTgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttendanceManageTgBtnActionPerformed(evt);
            }
        });
        nNavToolBar1.add(AttendanceManageTgBtn);

        add(nNavToolBar1, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        add(jPanel16, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void VacationTgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VacationTgBtnActionPerformed
        jPanel16.removeAll();
        jPanel16.setLayout(new BorderLayout());
        jPanel16.add(vacationMgmtPane, BorderLayout.CENTER);
        revalidate();
        repaint();        
    }//GEN-LAST:event_VacationTgBtnActionPerformed

    private void BizTripManageTgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BizTripManageTgBtnActionPerformed
       jPanel16.removeAll();
       jPanel16.setLayout(new BorderLayout());
       jPanel16.add(bizTripMgmtPane,BorderLayout.CENTER);
       revalidate();
       repaint();
    }//GEN-LAST:event_BizTripManageTgBtnActionPerformed

    private void RestManageTgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestManageTgBtnActionPerformed
       jPanel16.removeAll();
       jPanel16.setLayout(new BorderLayout());
       jPanel16.add(restMgmtPanel,BorderLayout.CENTER);
       revalidate();
       repaint();
    }//GEN-LAST:event_RestManageTgBtnActionPerformed

    private void AttendanceManageTgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttendanceManageTgBtnActionPerformed
        jPanel16.removeAll();
        jPanel16.setLayout(new BorderLayout());
        jPanel16.add(attendanceMgmtPanel,BorderLayout.CENTER);
        revalidate();
        repaint();
    }//GEN-LAST:event_AttendanceManageTgBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AttendanceManageTgBtn;
    private javax.swing.JToggleButton BizTripManageTgBtn;
    private javax.swing.JToggleButton RestManageTgBtn;
    private javax.swing.JToggleButton VacationTgBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel16;
    private com.nazca.ui.NNavToolBar nNavToolBar1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onInit() {
        vacationMgmtPane.init();
    }

    @Override
    public String getComponentUUID() {
        return AttendanceInfoMgmtTabPanel.class.getName();
    }

    @Override
    public void onDestroy() {
    }
    
    
    
    
    //TDOO
     public void init() {
        refreshBtnActionPerformed(null);
    }

    private void refreshBtnActionPerformed(Object object) {
    }
}
