/*
 * RulesPanel.java
 * 
 * Copyright(c) 2007-2016 by Yingzhi Tech
 * All Rights Reserved
 * 
 * Created at 2016-01-19 17:05:16
 */
package com.yz.ams.client.ui;

import com.yz.ams.client.ui.RulesMgmt.RulesMgmtPanel;
import com.yz.ams.client.ui.holiday.HolidayMgmtPanel;
import com.yz.ams.client.ui.team.TeamMgmtPanel;
import com.nazca.ui.NTabContentPanel;
import com.yz.ams.client.ui.PaidVacationMgmt.PaidVacationMgmtPanel;
import com.yz.ams.client.ui.UserMgmt.UserMgmtPanel;
import java.awt.BorderLayout;

/**
 *
 * @author Your Name <Song Haixiang >
 */
public class SystemMgmtTabPanel extends NTabContentPanel {
    private TeamMgmtPanel teamMgmtPane = null;
    //年假管理panel
    private PaidVacationMgmtPanel paidVacationMgmtPanel = null;
    //规则设定panel
    private RulesMgmtPanel rulesMgmtPanel = null;

    private HolidayMgmtPanel holidayMgmtPane = null;
    //用户管理面板
    private UserMgmtPanel  userMgmtPanel = null;
    /**
     * Creates new form RulesPanel
     */
    public SystemMgmtTabPanel() {
        initComponents();
        setTabText("系统设置");
        jPanel1.setLayout(new BorderLayout());
        teamMgmtPane = new TeamMgmtPanel();
        paidVacationMgmtPanel = new PaidVacationMgmtPanel();
        rulesMgmtPanel = new RulesMgmtPanel();
        holidayMgmtPane = new HolidayMgmtPanel();
        userMgmtPanel = new UserMgmtPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        nNavToolBar1 = new com.nazca.ui.NNavToolBar();
        RulesTgBtn = new javax.swing.JToggleButton();
        HolidayTgBtn = new javax.swing.JToggleButton();
        PaidVacationTgBtn = new javax.swing.JToggleButton();
        userManageBtn = new javax.swing.JToggleButton();
        TeamTgBtn = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();

        nNavToolBar1.setRollover(true);

        buttonGroup1.add(RulesTgBtn);
        RulesTgBtn.setText("规则设定");
        RulesTgBtn.setFocusable(false);
        RulesTgBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RulesTgBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RulesTgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RulesTgBtnActionPerformed(evt);
            }
        });
        nNavToolBar1.add(RulesTgBtn);

        buttonGroup1.add(HolidayTgBtn);
        HolidayTgBtn.setText("假期管理");
        HolidayTgBtn.setFocusable(false);
        HolidayTgBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        HolidayTgBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        HolidayTgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HolidayTgBtnActionPerformed(evt);
            }
        });
        nNavToolBar1.add(HolidayTgBtn);

        buttonGroup1.add(PaidVacationTgBtn);
        PaidVacationTgBtn.setText("年假管理");
        PaidVacationTgBtn.setFocusable(false);
        PaidVacationTgBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PaidVacationTgBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        PaidVacationTgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaidVacationTgBtnActionPerformed(evt);
            }
        });
        nNavToolBar1.add(PaidVacationTgBtn);

        buttonGroup1.add(userManageBtn);
        userManageBtn.setText("用户管理");
        userManageBtn.setFocusable(false);
        userManageBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userManageBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        userManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManageBtnActionPerformed(evt);
            }
        });
        nNavToolBar1.add(userManageBtn);

        buttonGroup1.add(TeamTgBtn);
        TeamTgBtn.setText("团队管理");
        TeamTgBtn.setFocusable(false);
        TeamTgBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TeamTgBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        TeamTgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamTgBtnActionPerformed(evt);
            }
        });
        nNavToolBar1.add(TeamTgBtn);

        add(nNavToolBar1, java.awt.BorderLayout.NORTH);
        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    //规则设定panel添加
    private void RulesTgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RulesTgBtnActionPerformed
       jPanel1.removeAll();
       jPanel1.add(rulesMgmtPanel ,BorderLayout.CENTER);
       revalidate();
       repaint();
    }//GEN-LAST:event_RulesTgBtnActionPerformed

    private void HolidayTgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HolidayTgBtnActionPerformed
        jPanel1.removeAll();
        jPanel1.add(holidayMgmtPane, BorderLayout.CENTER);
        holidayMgmtPane.init();
        revalidate();
        repaint();
    }//GEN-LAST:event_HolidayTgBtnActionPerformed
    
    //年假管理panel添加
    private void PaidVacationTgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaidVacationTgBtnActionPerformed
       jPanel1.removeAll();
       jPanel1.add(paidVacationMgmtPanel, BorderLayout.CENTER);
       revalidate();
       repaint();
    }//GEN-LAST:event_PaidVacationTgBtnActionPerformed

    private void TeamTgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamTgBtnActionPerformed
       jPanel1.removeAll();
       jPanel1.add(teamMgmtPane, BorderLayout.CENTER);
//       teamMgmtPane.init();
       revalidate();
       repaint();
    }//GEN-LAST:event_TeamTgBtnActionPerformed

    private void userManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManageBtnActionPerformed
       jPanel1.removeAll();
       jPanel1.add(userMgmtPanel, BorderLayout.CENTER);
       revalidate();
       repaint();
    }//GEN-LAST:event_userManageBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton HolidayTgBtn;
    private javax.swing.JToggleButton PaidVacationTgBtn;
    private javax.swing.JToggleButton RulesTgBtn;
    private javax.swing.JToggleButton TeamTgBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private com.nazca.ui.NNavToolBar nNavToolBar1;
    private javax.swing.JToggleButton userManageBtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onInit() {
        RulesTgBtn.doClick();
    }

    @Override
    public String getComponentUUID() {
        return SystemMgmtTabPanel.class.getName();
    }

    @Override
    public void onDestroy() {
    }
}
