/*
 * UsmInfoTreePanel.java
 * 
 * Copyright(c) 2007-2016 by Yingzhi Tech
 * All Rights Reserved
 * 
 * Created at 2016-03-11 15:16:10
 */
package com.yz.ams.client.ui;

import com.nazca.ui.NInternalDiag;
import com.nazca.usm.client.ui.api.UserSelectionPanel;
import com.nazca.usm.model.USMSUser;
import com.yz.ams.client.OKCancelPanelListener;
import com.yz.ams.client.util.ClientUtils;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JComponent;

/**
 *
 * @author Zhu Mengchao
 */
public class UsmInfoTreePanel extends javax.swing.JPanel {
    private NInternalDiag<List<USMSUser>, JComponent> diag;
    private UserSelectionPanel usp1 = null;
    private List<USMSUser> userList = null;

    /**
     * Creates new form UsmInfoTreePanel
     */
    public UsmInfoTreePanel() {
        initComponents();
        usp1 = new UserSelectionPanel(UserSelectionPanel.SELECTION_MODE_MUTI);
	usp1.init();
	this.add(usp1,BorderLayout.CENTER);
	
	oKCancelPanel1.addOKCancelListener(new OKCancelPanelListener() {

	    @Override
	    public void onOKClicked() {
		try {
		    userList = usp1.getSelectedUsers();
		} catch (Exception ex) {
		    ex.printStackTrace();
		}
		diag.hideDiag(userList);
	    }

	    @Override
	    public void onCancelClicked() {
		diag.hideDiag();
	    }
	});
    }
    
    public List<USMSUser> showMe(JComponent Parent) {
	    diag = new NInternalDiag<List<USMSUser>, JComponent>("选择人员",  ClientUtils.buildImageIcon("menber-list.png"), this, 750, 550);
	    return diag.showInternalDiag(Parent);
    }

    public List<USMSUser> getUserList() {
	return userList;
    }

    public void setUserList(List<USMSUser> userList) {
	this.userList = userList;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oKCancelPanel1 = new com.yz.ams.client.OKCancelPanel();

        setLayout(new java.awt.BorderLayout());
        add(oKCancelPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.yz.ams.client.OKCancelPanel oKCancelPanel1;
    // End of variables declaration//GEN-END:variables
}
