package com.yz.ams.client.ui.RulesMgmt;

import com.nazca.ui.NWaitingPanel;
import com.nazca.ui.UIUtilities;
import com.nazca.ui.laf.NTitledRoundSideUI;
import com.nazca.ui.util.CardLayoutWrapper;
import com.yz.ams.client.agent.AgentListener;
import com.yz.ams.client.agent.QueryRulesAgent;
import com.yz.ams.consts.SystemParamKey;
import com.yz.ams.model.SystemParam;
import java.util.List;

/*
 * RulesMgmtPanel.java
 * 
 * Copyright(c) 2007-2016 by Yingzhi Tech
 * All Rights Reserved
 * 
 * Created at 2016-01-11 11:25:32
 */

/**
 *规则管理面板
 * @author Your Name <zhaohongkun@yzhtech.com >
 */
public class RulesMgmtPanel extends javax.swing.JPanel {

     private QueryRulesAgent queryRulesAgent =null;
     public List<SystemParam> systemParamListOld = null;
     private CardLayoutWrapper card = null;
    /**
     * Creates new form SetReulePanel
     */
    public RulesMgmtPanel() {
        initComponents();
        initUI();
        initAgentAndListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        refreshBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cardLayoutPanel = new javax.swing.JPanel();
        systemParaPanel = new javax.swing.JPanel();
        workTimePanel = new javax.swing.JPanel();
        amStartTimeLb = new javax.swing.JLabel();
        amStartTimeTxFd = new javax.swing.JTextField();
        pmStartTimeLb = new javax.swing.JLabel();
        pmStartTimeTxFd = new javax.swing.JTextField();
        amEndTimeTxFd = new javax.swing.JTextField();
        amEndTimeLb = new javax.swing.JLabel();
        pmEndTimeLb = new javax.swing.JLabel();
        pmEndTimeTxFd = new javax.swing.JTextField();
        vacationDaysSetPanel = new javax.swing.JPanel();
        yearCountOneLb = new javax.swing.JLabel();
        yearCountOneTxFd = new javax.swing.JTextField();
        yearCountTwentyLb = new javax.swing.JLabel();
        yearCountTwentyTxFd = new javax.swing.JTextField();
        yearCountTenTxFd = new javax.swing.JTextField();
        yearCountTenLb = new javax.swing.JLabel();
        yearCountInnerLb = new javax.swing.JLabel();
        yearCountInnerTxFd = new javax.swing.JTextField();
        lateTimePanel = new javax.swing.JPanel();
        slightLateTxFd = new javax.swing.JTextField();
        slightLateLb = new javax.swing.JLabel();
        lateLb = new javax.swing.JLabel();
        seriousLateLb = new javax.swing.JLabel();
        seriousLateTxFd = new javax.swing.JTextField();
        lateTxFd = new javax.swing.JTextField();
        nWaitingPanel1 = new com.nazca.ui.NWaitingPanel();
        failedInfoPanel1 = new com.nazca.ui.FailedInfoPanel();

        setMinimumSize(new java.awt.Dimension(900, 0));
        setPreferredSize(new java.awt.Dimension(900, 385));
        setLayout(new java.awt.BorderLayout());

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);
        jToolBar2.setMaximumSize(new java.awt.Dimension(750, 23));

        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/yz/ams/client/res/refresh_16.png"))); // NOI18N
        refreshBtn.setText("刷新");
        refreshBtn.setFocusable(false);
        refreshBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        jToolBar2.add(refreshBtn);

        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/yz/ams/client/res/update-16.png"))); // NOI18N
        updateBtn.setText("修改");
        updateBtn.setFocusable(false);
        updateBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jToolBar2.add(updateBtn);

        add(jToolBar2, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        cardLayoutPanel.setLayout(new java.awt.CardLayout());

        systemParaPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        systemParaPanel.setLayout(new com.nazca.ui.layout.BoxLayout2());

        workTimePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        workTimePanel.setMaximumSize(new java.awt.Dimension(32767, 160));
        workTimePanel.setMinimumSize(new java.awt.Dimension(0, 160));
        workTimePanel.setOpaque(false);
        workTimePanel.setPreferredSize(new java.awt.Dimension(929, 160));

        amStartTimeLb.setFont(amStartTimeLb.getFont().deriveFont(amStartTimeLb.getFont().getSize()+2f));
        amStartTimeLb.setText("上午开始时间：");

        amStartTimeTxFd.setFont(amStartTimeTxFd.getFont().deriveFont(amStartTimeTxFd.getFont().getStyle() | java.awt.Font.BOLD, amStartTimeTxFd.getFont().getSize()+2));

        pmStartTimeLb.setFont(pmStartTimeLb.getFont().deriveFont(pmStartTimeLb.getFont().getSize()+2f));
        pmStartTimeLb.setText("下午开始时间：");

        pmStartTimeTxFd.setFont(pmStartTimeTxFd.getFont().deriveFont(pmStartTimeTxFd.getFont().getStyle() | java.awt.Font.BOLD, pmStartTimeTxFd.getFont().getSize()+2));

        amEndTimeTxFd.setFont(amEndTimeTxFd.getFont().deriveFont(amEndTimeTxFd.getFont().getStyle() | java.awt.Font.BOLD, amEndTimeTxFd.getFont().getSize()+2));

        amEndTimeLb.setFont(amEndTimeLb.getFont().deriveFont(amEndTimeLb.getFont().getSize()+2f));
        amEndTimeLb.setText("上午结束时间：");

        pmEndTimeLb.setFont(pmEndTimeLb.getFont().deriveFont(pmEndTimeLb.getFont().getSize()+2f));
        pmEndTimeLb.setText("下午结束时间：");

        pmEndTimeTxFd.setFont(pmEndTimeTxFd.getFont().deriveFont(pmEndTimeTxFd.getFont().getStyle() | java.awt.Font.BOLD, pmEndTimeTxFd.getFont().getSize()+2));

        javax.swing.GroupLayout workTimePanelLayout = new javax.swing.GroupLayout(workTimePanel);
        workTimePanel.setLayout(workTimePanelLayout);
        workTimePanelLayout.setHorizontalGroup(
            workTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workTimePanelLayout.createSequentialGroup()
                .addGroup(workTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amStartTimeLb)
                    .addGroup(workTimePanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(pmStartTimeLb)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(workTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amStartTimeTxFd, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addComponent(pmStartTimeTxFd))
                .addGap(97, 97, 97)
                .addGroup(workTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pmEndTimeLb, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(amEndTimeLb, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(workTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amEndTimeTxFd, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(pmEndTimeTxFd))
                .addGap(57, 57, 57))
        );
        workTimePanelLayout.setVerticalGroup(
            workTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workTimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(workTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amStartTimeLb)
                    .addComponent(amStartTimeTxFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amEndTimeLb)
                    .addComponent(amEndTimeTxFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(workTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pmStartTimeLb)
                    .addComponent(pmStartTimeTxFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pmEndTimeLb)
                    .addComponent(pmEndTimeTxFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        systemParaPanel.add(workTimePanel);

        vacationDaysSetPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        vacationDaysSetPanel.setMaximumSize(new java.awt.Dimension(32767, 160));
        vacationDaysSetPanel.setMinimumSize(new java.awt.Dimension(0, 160));
        vacationDaysSetPanel.setOpaque(false);
        vacationDaysSetPanel.setPreferredSize(new java.awt.Dimension(929, 160));

        yearCountOneLb.setFont(yearCountOneLb.getFont().deriveFont(yearCountOneLb.getFont().getSize()+2f));
        yearCountOneLb.setText("1年至10年：");

        yearCountOneTxFd.setFont(yearCountOneTxFd.getFont().deriveFont(yearCountOneTxFd.getFont().getStyle() | java.awt.Font.BOLD, yearCountOneTxFd.getFont().getSize()+2));

        yearCountTwentyLb.setFont(yearCountTwentyLb.getFont().deriveFont(yearCountTwentyLb.getFont().getSize()+2f));
        yearCountTwentyLb.setText("20年以上：");

        yearCountTwentyTxFd.setFont(yearCountTwentyTxFd.getFont().deriveFont(yearCountTwentyTxFd.getFont().getStyle() | java.awt.Font.BOLD, yearCountTwentyTxFd.getFont().getSize()+2));

        yearCountTenTxFd.setFont(yearCountTenTxFd.getFont().deriveFont(yearCountTenTxFd.getFont().getStyle() | java.awt.Font.BOLD, yearCountTenTxFd.getFont().getSize()+2));

        yearCountTenLb.setFont(yearCountTenLb.getFont().deriveFont(yearCountTenLb.getFont().getSize()+2f));
        yearCountTenLb.setText("10年至20年：");

        yearCountInnerLb.setFont(yearCountInnerLb.getFont().deriveFont(yearCountInnerLb.getFont().getSize()+2f));
        yearCountInnerLb.setText("公司内部年假：");

        yearCountInnerTxFd.setFont(yearCountInnerTxFd.getFont().deriveFont(yearCountInnerTxFd.getFont().getStyle() | java.awt.Font.BOLD, yearCountInnerTxFd.getFont().getSize()+2));

        javax.swing.GroupLayout vacationDaysSetPanelLayout = new javax.swing.GroupLayout(vacationDaysSetPanel);
        vacationDaysSetPanel.setLayout(vacationDaysSetPanelLayout);
        vacationDaysSetPanelLayout.setHorizontalGroup(
            vacationDaysSetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vacationDaysSetPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(vacationDaysSetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(vacationDaysSetPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(yearCountTwentyLb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearCountTwentyTxFd, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
                    .addGroup(vacationDaysSetPanelLayout.createSequentialGroup()
                        .addComponent(yearCountOneLb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearCountOneTxFd, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)))
                .addGap(106, 106, 106)
                .addGroup(vacationDaysSetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yearCountInnerLb, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(yearCountTenLb, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vacationDaysSetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yearCountTenTxFd, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(yearCountInnerTxFd))
                .addGap(26, 26, 26))
        );
        vacationDaysSetPanelLayout.setVerticalGroup(
            vacationDaysSetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vacationDaysSetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vacationDaysSetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearCountOneLb)
                    .addComponent(yearCountOneTxFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearCountTenLb)
                    .addComponent(yearCountTenTxFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(vacationDaysSetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearCountTwentyLb)
                    .addComponent(yearCountTwentyTxFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearCountInnerLb)
                    .addComponent(yearCountInnerTxFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        systemParaPanel.add(vacationDaysSetPanel);

        lateTimePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        lateTimePanel.setMaximumSize(new java.awt.Dimension(32767, 160));
        lateTimePanel.setMinimumSize(new java.awt.Dimension(0, 160));
        lateTimePanel.setName(""); // NOI18N
        lateTimePanel.setPreferredSize(new java.awt.Dimension(929, 160));

        slightLateTxFd.setFont(slightLateTxFd.getFont().deriveFont(slightLateTxFd.getFont().getStyle() | java.awt.Font.BOLD, slightLateTxFd.getFont().getSize()+2));

        slightLateLb.setFont(slightLateLb.getFont().deriveFont(slightLateLb.getFont().getSize()+2f));
        slightLateLb.setText("轻微迟到：");

        lateLb.setFont(lateLb.getFont().deriveFont(lateLb.getFont().getSize()+2f));
        lateLb.setText("迟到：");

        seriousLateLb.setFont(seriousLateLb.getFont().deriveFont(seriousLateLb.getFont().getSize()+2f));
        seriousLateLb.setText("严重迟到：");

        seriousLateTxFd.setFont(seriousLateTxFd.getFont().deriveFont(seriousLateTxFd.getFont().getStyle() | java.awt.Font.BOLD, seriousLateTxFd.getFont().getSize()+2));
        seriousLateTxFd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seriousLateTxFdActionPerformed(evt);
            }
        });

        lateTxFd.setFont(lateTxFd.getFont().deriveFont(lateTxFd.getFont().getStyle() | java.awt.Font.BOLD, lateTxFd.getFont().getSize()+2));

        javax.swing.GroupLayout lateTimePanelLayout = new javax.swing.GroupLayout(lateTimePanel);
        lateTimePanel.setLayout(lateTimePanelLayout);
        lateTimePanelLayout.setHorizontalGroup(
            lateTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lateTimePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(lateTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seriousLateLb)
                    .addComponent(slightLateLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lateTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seriousLateTxFd, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(slightLateTxFd, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                .addGap(177, 177, 177)
                .addComponent(lateLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lateTxFd, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addGap(46, 46, 46))
        );
        lateTimePanelLayout.setVerticalGroup(
            lateTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lateTimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lateTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slightLateLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(slightLateTxFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lateLb)
                    .addComponent(lateTxFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lateTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seriousLateLb)
                    .addComponent(seriousLateTxFd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        systemParaPanel.add(lateTimePanel);

        cardLayoutPanel.add(systemParaPanel, "CONTENT");
        cardLayoutPanel.add(nWaitingPanel1, "WAIT");
        cardLayoutPanel.add(failedInfoPanel1, "FAIL");

        jScrollPane1.setViewportView(cardLayoutPanel);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed

        queryRulesAgent = new QueryRulesAgent();
        queryRulesAgent.addListener(querySystemParamAgentLis);
        queryRulesAgent.start();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed

        ModifyRulesPanel editPane = new ModifyRulesPanel();
        editPane.initPaneContent(systemParamListOld);
        List<SystemParam> systemParam = editPane.showMe(this);
        if (systemParam != null) {
            refreshBtnActionPerformed(evt);
        }

    }//GEN-LAST:event_updateBtnActionPerformed

    private void seriousLateTxFdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seriousLateTxFdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seriousLateTxFdActionPerformed
    private void initUI() {       
    //    systemParaPanel1.initUI();      
         //输入框变成无边框
        UIUtilities.makeItLikeLabel(amStartTimeTxFd);
        UIUtilities.makeItLikeLabel(amEndTimeTxFd);
        UIUtilities.makeItLikeLabel(pmStartTimeTxFd);
        UIUtilities.makeItLikeLabel(pmEndTimeTxFd);
        UIUtilities.makeItLikeLabel(slightLateTxFd);
        UIUtilities.makeItLikeLabel(lateTxFd);
        UIUtilities.makeItLikeLabel(seriousLateTxFd);
        UIUtilities.makeItLikeLabel(yearCountOneTxFd);
        UIUtilities.makeItLikeLabel(yearCountTenTxFd);
        UIUtilities.makeItLikeLabel(yearCountTwentyTxFd);
        UIUtilities.makeItLikeLabel(yearCountInnerTxFd);
        
        //添加cardpanel
        card = new CardLayoutWrapper(cardLayoutPanel);
        
        //设置工作时间、迟到时间、和年假天数面板的标题及圆角边框的样式
        workTimePanel.setUI(new NTitledRoundSideUI("上班时间设定")); 
        lateTimePanel.setUI(new NTitledRoundSideUI("迟到时间设定")); 
        vacationDaysSetPanel.setUI(new NTitledRoundSideUI("年假天数设定")); 
    }
    private void setBtnEnabled(boolean enabled) {
        refreshBtn.setEnabled(enabled);
        updateBtn.setEnabled(enabled);
    }
    /**
     * 填充规则管理面板的数据
     * @param syss 
     */
    public void fillRulesPane(List<SystemParam> syss) {
        systemParamListOld = syss;
        for(int i=0;i<syss.size();i++){
         //上午开始时间
        if(syss.get(i).getParamKey().name().equals(SystemParamKey.WORK_START_TIME_AM.name())){
            amStartTimeTxFd.setText(syss.get(i).getParamValue());
        }
        //上午结束时间
        if(syss.get(i).getParamKey().name().equals(SystemParamKey.WORK_END_TIME_AM.name())){
            amEndTimeTxFd.setText(syss.get(i).getParamValue());
        }
        //下午开始时间
        if(syss.get(i).getParamKey().name().equals(SystemParamKey.WORK_START_TIME_PM.name())){
            pmStartTimeTxFd.setText(syss.get(i).getParamValue());
        }
        //下午结束时间
        if(syss.get(i).getParamKey().name().equals(SystemParamKey.WORK_END_TIME_PM.name())){
            pmEndTimeTxFd.setText(syss.get(i).getParamValue());
        }
        //轻微迟到
        if(syss.get(i).getParamKey().name().equals(SystemParamKey.LIGHT_DELAY_MINUTES.name())){
            if(!syss.get(i).getParamValue().equals("")){
            slightLateTxFd.setText(syss.get(i).getParamValue()+"分钟以上");}else{
            slightLateTxFd.setText("0"+"分钟以上");
            }
        }
        //迟到
        if(syss.get(i).getParamKey().name().equals(SystemParamKey.NORMAL_DELAY_MINUTES.name())){
             if(!syss.get(i).getParamValue().equals("")){
            lateTxFd.setText(syss.get(i).getParamValue()+"分钟以上");}else{
            lateTxFd.setText("0"+"分钟以上");
            }
        }
        //严重迟到
        if(syss.get(i).getParamKey().name().equals(SystemParamKey.SERIOUS_DELAY_MINUTES.name())){
            if(!syss.get(i).getParamValue().equals("")){
            seriousLateTxFd.setText(syss.get(i).getParamValue()+"分钟以上");}else{
            seriousLateTxFd.setText("0"+"分钟以上");
            }
        }
        //1-10年
        if(syss.get(i).getParamKey().name().equals(SystemParamKey.PAID_VACATION_ONE_YEAR.name())){
            if(!syss.get(i).getParamValue().equals("")){
            yearCountOneTxFd.setText(syss.get(i).getParamValue()+"天");}else{
            yearCountOneTxFd.setText("0"+"天");
            }
        }
        //10-20年
        if(syss.get(i).getParamKey().name().equals(SystemParamKey.PAID_VACATION_TEN_YEAR.name())){
            if(!syss.get(i).getParamValue().equals("")){
            yearCountTenTxFd.setText(syss.get(i).getParamValue()+"天");}else{
            yearCountTenTxFd.setText("0"+"天");
            }
        }
        //20年
        if(syss.get(i).getParamKey().name().equals(SystemParamKey.PAID_VACATION_TWENTY_YEAR.name())){
            if(!syss.get(i).getParamValue().equals("")){
            yearCountTwentyTxFd.setText(syss.get(i).getParamValue()+"天");}else{
            yearCountTwentyTxFd.setText("0"+"天");
            }
        }
        //内部年假
        if(syss.get(i).getParamKey().name().equals(SystemParamKey.PAID_VACATION_INNER.name())){
            if(!syss.get(i).getParamValue().equals("")){
            yearCountInnerTxFd.setText(syss.get(i).getParamValue()+"天");}else{
            yearCountInnerTxFd.setText("0"+"天");
            }
        }
        
        }
    }
    
    public void initAgentAndListener() {//监听
        queryRulesAgent = new QueryRulesAgent();
        queryRulesAgent.addListener(querySystemParamAgentLis);
        queryRulesAgent.start();
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amEndTimeLb;
    private javax.swing.JTextField amEndTimeTxFd;
    private javax.swing.JLabel amStartTimeLb;
    private javax.swing.JTextField amStartTimeTxFd;
    private javax.swing.JPanel cardLayoutPanel;
    private com.nazca.ui.FailedInfoPanel failedInfoPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel lateLb;
    private javax.swing.JPanel lateTimePanel;
    private javax.swing.JTextField lateTxFd;
    private com.nazca.ui.NWaitingPanel nWaitingPanel1;
    private javax.swing.JLabel pmEndTimeLb;
    private javax.swing.JTextField pmEndTimeTxFd;
    private javax.swing.JLabel pmStartTimeLb;
    private javax.swing.JTextField pmStartTimeTxFd;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JLabel seriousLateLb;
    private javax.swing.JTextField seriousLateTxFd;
    private javax.swing.JLabel slightLateLb;
    private javax.swing.JTextField slightLateTxFd;
    private javax.swing.JPanel systemParaPanel;
    private javax.swing.JButton updateBtn;
    private javax.swing.JPanel vacationDaysSetPanel;
    private javax.swing.JPanel workTimePanel;
    private javax.swing.JLabel yearCountInnerLb;
    private javax.swing.JTextField yearCountInnerTxFd;
    private javax.swing.JLabel yearCountOneLb;
    private javax.swing.JTextField yearCountOneTxFd;
    private javax.swing.JLabel yearCountTenLb;
    private javax.swing.JTextField yearCountTenTxFd;
    private javax.swing.JLabel yearCountTwentyLb;
    private javax.swing.JTextField yearCountTwentyTxFd;
    // End of variables declaration//GEN-END:variables
    private AgentListener<List<SystemParam>> querySystemParamAgentLis = new AgentListener<List<SystemParam>>() {//监听
        @Override//监听
        public void onStarted(long seq) {
            setBtnEnabled(false);
            nWaitingPanel1.showWaitingMode("数据加载中，请稍后…");
            nWaitingPanel1.setIndeterminate(true);
            nWaitingPanel1.showWaitingMode();
            card.show(CardLayoutWrapper.WAIT);     
        }
          @Override
         public void onSucceeded(List<SystemParam> result, long seq) {
             systemParamListOld = result;
              if(result != null && result.size()> 0){  
                   nWaitingPanel1.setIndeterminate(false);
                   card.show(CardLayoutWrapper.CONTENT);
                  systemParamListOld = result;
                  fillRulesPane(result);
              }else{
                  nWaitingPanel1.showMsgMode("暂无规则信息", 0, NWaitingPanel.MSG_MODE_INFO);
                  card.show(CardLayoutWrapper.WAIT);
              }
           setBtnEnabled(true);
         }
         @Override
         public void onFailed(String errMsg, int errCode, long seq) {
            setBtnEnabled(true);
            nWaitingPanel1.showMsgMode(errMsg, errCode, NWaitingPanel.MSG_MODE_ERROR);
            card.show(CardLayoutWrapper.FAIL);
            nWaitingPanel1.setIndeterminate(false);
         }
         
            };
        }

